fix in release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -60,7 +60,15 @@ jobs:
           robocopy "${{ github.workspace }}/CodeWalker.API/bin/Release/net9.0" "${{ github.workspace }}/flat-output" /E || exit 0
           echo "Contents of flat-output:"
           dir "${{ github.workspace }}/flat-output"
+               echo "Creating ZIP..."
           powershell Compress-Archive -Path "${{ github.workspace }}/flat-output/*" -DestinationPath "${{ github.workspace }}/CodeWalker.API.zip"
+               echo "Checking if ZIP file exists:"
+          if not exist "${{ github.workspace }}/CodeWalker.API.zip" (
+              echo "❌ ERROR: ZIP file was not created!"
+              exit 1
+          ) else (
+              echo "✅ ZIP file created successfully."
+          )
 
       - name: Upload Release
         uses: softprops/action-gh-release@v2
